use_frameworks!

target 'RACProgressSubject_Example' do
  pod 'RACProgressSubject', :path => '../'

end

target 'RACProgressSubject_Tests' do
  pod 'RACProgressSubject', :path => '../'

  pod 'Kiwi'
end
