codecov:
  branch: master
  bot: null

coverage:
  precision: 2
  round: down
  range: "70...100"

  ignore:               # files and folders that will be removed during processing
    - "Example/*"
