# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c

cache:
  - bundler
  - cocoapods

before_install: rvm use $RVM_RUBY_VERSION

install:
  - bundle install --without=documentation --path ../travis_bundle_dir
  # too slow
  #- bundle exec pod repo update --silent
  - bundle exec pod install --project-directory=Example

script:
  - set -o pipefail && xcodebuild test -workspace Example/RACProgressSubject.xcworkspace -scheme RACProgressSubject-Example -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6' ONLY_ACTIVE_ARCH=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES | xcpretty -c

# -c means coverall
# -t means travis
# -s means simple output
after_success: cd $TRAVIS_BUILD_DIR && slather
